; [db]
; driver = mysql
; db_name = chat_app
; user = root
; password = root
; host = localhost  ; ローカル環境でアプリを起動する場合
; ; host = db  ; ローカルでdockerコンテナを使用する場合
; port = 3306

; [api]
; domain = localhost  ; ローカル環境でアプリを起動する場合
; ; domain = 0.0.0.0  ; ローカルでdockerコンテナを使用する場合
; port = 8080

; [fe]
; url = http://localhost:3000



[db]
driver = mysql
db_name = chat_app
user = root
password = root
host = db
port = 3306

[api]
; domain = https://api.schaty.net
domain = schaty.net  ; cookieを両方のサブドメインで共有するためメインドメインを指定（cookieのドメイン指定のみで使用されているため）
port = 8080
certFile = "/etc/letsencrypt/live/your_domain/fullchain.pem"
keyFile = "/etc/letsencrypt/live/your_domain/privkey.pem"


[fe]
url = https://schaty.net