version: '3.8'

services:
  app:
    build: .
    container_name: chat_app
    ports:
      - "${PORT}:${PORT}"
      - "${GRPC_PORT}:${GRPC_PORT}"
    volumes:
      - ./certs/privkey.pem:/etc/letsencrypt/live/api.${BACK_SERVER_DOMAIN}/privkey.pem:ro
      - ./certs/fullchain.pem:/etc/letsencrypt/live/api.${BACK_SERVER_DOMAIN}/fullchain.pem:ro
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: chat_app
      TZ: Asia/Tokyo
    #command: sh -c "/app/migrate && /app/main"  # MEMO: 初回起動時
    command: sh -c "/app/main"
    networks:
      - app-network

  db:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: chat_app
      TZ: Asia/Tokyo
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network: